// 自动生成 - 请勿手动修改
// 生成时间: 2026-08-30 13:43:33

var ordersData = [
  {
    "date": "2026-06-01",
    "month": "6月",
    "sales": "丁露",
    "customer": "吕剑辉",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-06-03",
    "month": "6月",
    "sales": "乔浩",
    "customer": "上海生泰电器有限公司",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-06-03",
    "month": "6月",
    "sales": "董逸亭",
    "customer": "虞署民",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "外牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-06-04",
    "month": "6月",
    "sales": "罗松",
    "customer": "杨艳",
    "car": "M7 EV",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-06-06",
    "month": "6月",
    "sales": "任天翔",
    "customer": "桂强礼",
    "car": "M7 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-06-07",
    "month": "6月",
    "sales": "丁露",
    "customer": "张华华",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-06-07",
    "month": "6月",
    "sales": "丁露",
    "customer": "何蓓蓓",
    "car": "M6 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-07",
    "month": "6月",
    "sales": "乔浩",
    "customer": "叶飞",
    "car": "M9 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-06-01",
    "month": "6月",
    "sales": "罗松",
    "customer": "徐彬",
    "car": "M6 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-11",
    "month": "6月",
    "sales": "乔浩",
    "customer": "张骏骋",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-14",
    "month": "6月",
    "sales": "董逸亭",
    "customer": "黄云方",
    "car": "M8 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1400,
    "mgr_commission": 700,
    "status": "正常"
  },
  {
    "date": "2026-06-02",
    "month": "6月",
    "sales": "董逸亭",
    "customer": "张职艳",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-02",
    "month": "6月",
    "sales": "任天翔",
    "customer": "张嘉杰",
    "car": "M9 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "公司大牌",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-06-02",
    "month": "6月",
    "sales": "董逸亭",
    "customer": "张洁",
    "car": "Z7T",
    "brand": "尚界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-06-02",
    "month": "6月",
    "sales": "任天翔",
    "customer": "倪晨",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-02",
    "month": "6月",
    "sales": "董逸亭",
    "customer": "陈文莹",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-21",
    "month": "6月",
    "sales": "乔浩",
    "customer": "魏进红",
    "car": "M8 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1400,
    "mgr_commission": 700,
    "status": "正常"
  },
  {
    "date": "2026-06-27",
    "month": "6月",
    "sales": "丁露",
    "customer": "张燕",
    "car": "Z7",
    "brand": "尚界",
    "plate": "",
    "order_no": "",
    "review": "是",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-06-27",
    "month": "6月",
    "sales": "乔浩",
    "customer": "韩璐",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-28",
    "month": "6月",
    "sales": "任天翔",
    "customer": "刘德雄",
    "car": "M7 EV",
    "brand": "问界",
    "plate": "免费公牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-06-28",
    "month": "6月",
    "sales": "乔浩",
    "customer": "王震",
    "car": "S9T EV",
    "brand": "享界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 2000,
    "mgr_commission": 1000,
    "status": "正常"
  },
  {
    "date": "2026-06-29",
    "month": "6月",
    "sales": "罗松",
    "customer": "杨家荣",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-06-30",
    "month": "6月",
    "sales": "董逸亭",
    "customer": "张广荣",
    "car": "M9 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-06-30",
    "month": "6月",
    "sales": "罗松",
    "customer": "归龙法",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "",
    "order_no": "",
    "review": "",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-07-04",
    "month": "7月",
    "sales": "乔浩",
    "customer": "魏进红",
    "car": "M8 EV",
    "brand": "问界",
    "plate": "免费公牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1400,
    "mgr_commission": 700,
    "status": "正常"
  },
  {
    "date": "2026-07-06",
    "month": "7月",
    "sales": "罗松",
    "customer": "周毛女",
    "car": "M8 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1400,
    "mgr_commission": 700,
    "status": "正常"
  },
  {
    "date": "2026-07-06",
    "month": "7月",
    "sales": "丁露",
    "customer": "龚顺明",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-07-09",
    "month": "7月",
    "sales": "乔浩",
    "customer": "卢梦霞",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-07-12",
    "month": "7月",
    "sales": "乔浩",
    "customer": "方兵",
    "car": "M7 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-07-12",
    "month": "7月",
    "sales": "任天翔",
    "customer": "于硕",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-07-19",
    "month": "7月",
    "sales": "丁露",
    "customer": "李蓉",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-07-19",
    "month": "7月",
    "sales": "丁露",
    "customer": "刘俊伟",
    "car": "M7 EVR",
    "brand": "问界",
    "plate": "大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-07-19",
    "month": "7月",
    "sales": "乔浩",
    "customer": "宋一立",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "免费公牌",
    "order_no": "",
    "review": "",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-07-19",
    "month": "7月",
    "sales": "任天翔",
    "customer": "吕立强",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-07-22",
    "month": "7月",
    "sales": "罗松",
    "customer": "欧阳清",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-07-23",
    "month": "7月",
    "sales": "乔浩",
    "customer": "阎珺",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 800,
    "mgr_commission": 400,
    "status": "正常"
  },
  {
    "date": "2026-07-24",
    "month": "7月",
    "sales": "乔浩",
    "customer": "宋佳敏",
    "car": "H5 EV",
    "brand": "尚界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1000,
    "mgr_commission": 500,
    "status": "正常"
  },
  {
    "date": "2026-07-25",
    "month": "7月",
    "sales": "罗松",
    "customer": "段云祥",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "",
    "sale_commission": 1600,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-07-26",
    "month": "7月",
    "sales": "罗松",
    "customer": "周增光",
    "car": "M7 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "",
    "sale_commission": 1200,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-08-02",
    "month": "8月",
    "sales": "罗松",
    "customer": "王彤",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "免费绿牌",
    "order_no": "",
    "review": "",
    "sale_commission": 800,
    "mgr_commission": 500,
    "status": "正常"
  },
  {
    "date": "2026-08-02",
    "month": "8月",
    "sales": "丁露",
    "customer": "申光迎",
    "car": "H5 EVR",
    "brand": "尚界",
    "plate": "外牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 800,
    "mgr_commission": 500,
    "status": "正常"
  },
  {
    "date": "2026-08-04",
    "month": "8月",
    "sales": "罗松",
    "customer": "王彦雯",
    "car": "M6 EV",
    "brand": "问界",
    "plate": "个人大牌",
    "order_no": "",
    "review": "不需要",
    "sale_commission": 800,
    "mgr_commission": 500,
    "status": "正常"
  },
  {
    "date": "2026-08-13",
    "month": "8月",
    "sales": "丁露",
    "customer": "上海娄星工具有限公司",
    "car": "M9 EV",
    "brand": "问界",
    "plate": "免费公牌",
    "order_no": "",
    "review": "是",
    "sale_commission": 1400,
    "mgr_commission": 800,
    "status": "正常"
  },
  {
    "date": "2026-08-16",
    "month": "8月",
    "sales": "丁露",
    "customer": "纪静静",
    "car": "M7 EVR",
    "brand": "问界",
    "plate": "外牌",
    "order_no": "2873365515247985.0",
    "review": "不需要",
    "sale_commission": 1000,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-08-19",
    "month": "8月",
    "sales": "任天翔",
    "customer": "徐华平",
    "car": "M7 EVR",
    "brand": "问界",
    "plate": "个人大牌",
    "order_no": "2873366397657957.0",
    "review": "不需要",
    "sale_commission": 1000,
    "mgr_commission": 600,
    "status": "正常"
  },
  {
    "date": "2026-08-20",
    "month": "8月",
    "sales": "丁露",
    "customer": "谭韡",
    "car": "G9",
    "brand": "享界",
    "plate": "免费公牌",
    "order_no": "2873350598354643.0",
    "review": "",
    "sale_commission": 3000,
    "mgr_commission": 1500,
    "status": "正常"
  },
  {
    "date": "2026-08-22",
    "month": "8月",
    "sales": "任天翔",
    "customer": "程世玉",
    "car": "Z7T",
    "brand": "尚界",
    "plate": "免费公牌",
    "order_no": "2873371458461898.0",
    "review": "",
    "sale_commission": 1400,
    "mgr_commission": 800,
    "status": "正常"
  }
];

var commissionData = {
  "7月": {
    "sales": [
      {
        "name": "罗松",
        "target": 2,
        "order_count": 4,
        "rate": 2.0,
        "coeff": 1.2,
        "sale_commission": 5000,
        "mgr_commission": 2500,
        "final_commission": 6000
      },
      {
        "name": "乔浩",
        "target": 3,
        "order_count": 6,
        "rate": 2.0,
        "coeff": 1.2,
        "sale_commission": 6800,
        "mgr_commission": 3400,
        "final_commission": 8160
      },
      {
        "name": "丁露",
        "target": 2,
        "order_count": 3,
        "rate": 1.5,
        "coeff": 1.2,
        "sale_commission": 3600,
        "mgr_commission": 1800,
        "final_commission": 4320
      },
      {
        "name": "任天翔",
        "target": 2,
        "order_count": 2,
        "rate": 1.0,
        "coeff": 1.0,
        "sale_commission": 1600,
        "mgr_commission": 800,
        "final_commission": 1600
      },
      {
        "name": "刘洋",
        "target": 0,
        "order_count": 0,
        "rate": 0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      }
    ],
    "manager": {
      "name": "周志鹏",
      "target": 9,
      "order_count": 15,
      "rate": 1.667,
      "coeff": 1.2,
      "commission_base": 8500,
      "final_commission": 10200
    }
  },
  "8月": {
    "sales": [
      {
        "name": "罗松",
        "target": 3,
        "order_count": 2,
        "rate": 0.667,
        "coeff": 1.0,
        "sale_commission": 1600,
        "mgr_commission": 1000,
        "final_commission": 1600
      },
      {
        "name": "乔浩",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 1.0,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "丁露",
        "target": 3,
        "order_count": 4,
        "rate": 1.333,
        "coeff": 1.0,
        "sale_commission": 6200,
        "mgr_commission": 3400,
        "final_commission": 6200
      },
      {
        "name": "任天翔",
        "target": 3,
        "order_count": 2,
        "rate": 0.667,
        "coeff": 1.0,
        "sale_commission": 2400,
        "mgr_commission": 1400,
        "final_commission": 2400
      },
      {
        "name": "刘洋",
        "target": 1,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 1.0,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      }
    ],
    "manager": {
      "name": "周志鹏",
      "target": 13,
      "order_count": 8,
      "rate": 0.615,
      "coeff": 0.7,
      "commission_base": 5800,
      "final_commission": 4060
    }
  },
  "9月": {
    "sales": [
      {
        "name": "罗松",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "乔浩",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "丁露",
        "target": 2,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "任天翔",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "刘洋",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      }
    ],
    "manager": {
      "name": "周志鹏",
      "target": 14,
      "order_count": 0,
      "rate": 0.0,
      "coeff": 0.5,
      "commission_base": 0,
      "final_commission": 0
    }
  },
  "10月": {
    "sales": [
      {
        "name": "罗松",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "乔浩",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "丁露",
        "target": 2,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "任天翔",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "刘洋",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      }
    ],
    "manager": {
      "name": "周志鹏",
      "target": 14,
      "order_count": 0,
      "rate": 0.0,
      "coeff": 0.5,
      "commission_base": 0,
      "final_commission": 0
    }
  },
  "11月": {
    "sales": [
      {
        "name": "罗松",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "乔浩",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "丁露",
        "target": 2,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "任天翔",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "刘洋",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      }
    ],
    "manager": {
      "name": "周志鹏",
      "target": 14,
      "order_count": 0,
      "rate": 0.0,
      "coeff": 0.5,
      "commission_base": 0,
      "final_commission": 0
    }
  },
  "12月": {
    "sales": [
      {
        "name": "罗松",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "乔浩",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "丁露",
        "target": 2,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "任天翔",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      },
      {
        "name": "刘洋",
        "target": 3,
        "order_count": 0,
        "rate": 0.0,
        "coeff": 0.5,
        "sale_commission": 0,
        "mgr_commission": 0,
        "final_commission": 0
      }
    ],
    "manager": {
      "name": "周志鹏",
      "target": 14,
      "order_count": 0,
      "rate": 0.0,
      "coeff": 0.5,
      "commission_base": 0,
      "final_commission": 0
    }
  }
};
